services:
  cosyvoice:
    image: voice:v0.7.0
#    build:
#      context: .
#      dockerfile: Dockerfile
    container_name: cosyvoice
    ports:
      - "50000:50000"
    environment:
      - HF_ENDPOINT=https://hf-mirror.com
    command:
      - "python3"
      - "main.py"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    restart: unless-stopped