services:
  cosyvoice:
#    image: chise/cosyvoice:v0.1
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./pretrained_models:/opt/CosyVoice/pretrained_models
      - ./cache:/root/.cache
    container_name: cosyvoice
    ports:
      - "50000:50000"
    environment:
      - HF_ENDPOINT=https://hf-mirror.com
    command:
      - "python"
      - "app.py"
      - "--model_dir=pretrained_models/CosyVoice2-0.5B"
    restart: unless-stopped