services:
  cosyvoice:
    image: voice:v0.4.0
#    build:
#      context: .
#      dockerfile: Dockerfile
    volumes:
      - ./pretrained_models:/opt/CosyVoice/pretrained_models
      - ./third_party:/opt/CosyVoice/third_party
      - ./cache:/root/.cache
      - ./triton:/root.triton
    container_name: cosyvoice
    ports:
      - "50000:50000"
    environment:
      - HF_ENDPOINT=https://hf-mirror.com
    command:
      - "python3"
      - "app.py"
      - "--model_dir=pretrained_models/CosyVoice2-0.5B"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    restart: unless-stopped