version: '3'

services:
  cosyvoice:
    image: cosyvoice:v0.1
    volumes:
      - C:\Users\chise\Documents\project\CosyVoice\pretrained_models:/opt/CosyVoice/pretrained_models
    container_name: cosyvoice
    ports:
      - "50000:50000"
    environment:
      - HF_ENDPOINT=https://hf-mirror.com
    command:
      - "python"
      - "runtime/fastapi/server.py"
      - "--model_dir"
      - "pretrained_models/CosyVoice2-0.5B"
    restart: unless-stopped